### ISSUE TITLE
checking attributions of many GBIF occurrenceIDs with one api request

### ISSUE THREAD

**Issue by abubelinha** [bionomia/bionomia-api#4]
Is there any way of using current api to check attribution status of many gbif occurrence records with just one request?

Currently I only see this option (just one record per request):
https://api.bionomia.net/occurrence/1935887248.jsonld

Thanks
@abubelinha

**Comment by dshorthouse** [comment]
Not at present because the output is unlikely to be JSON-LD; representing arrays of object, each of whose keys are predicates is ghastly. Any suggestions on what the output should or could be?

**Comment by abubelinha** [comment]
No idea. Just wondering if it was possible.

If #3 becomes possible, then it might be useful to first check which of my occurrenceIDs have already been attributed in bionomia (to avoid providing you repeated useless data).
